- name: Install cli packages
  become: true
  community.general.pacman:
    name:
      - bash-completion
      - btop
      - neofetch
      - exa
      - bat
      - fzf
      - bc
      - zip
      - nmap
      - tcpdump
      - fwupd

- name: Copy bat bashrc
  ansible.builtin.copy:
    src: bat.bashrc
    dest: ~/.bashrc.d/
    mode: '0644'

- name: Copy exa bashrc
  ansible.builtin.copy:
    src: exa.bashrc
    dest: ~/.bashrc.d/
    mode: '0644'

- name: Copy fzf bashrc
  ansible.builtin.copy:
    src: fzf.bashrc
    dest: ~/.bashrc.d/
    mode: '0644'
