- name: Install editor packages
  become: true
  community.general.pacman:
    name:
      - neovim
      - lazygit
      - ripgrep
      - bottom
      - gdu

- name: Copy vim bash_profile
  ansible.builtin.copy:
    src: vim.bash_profile
    dest: ~/.bash_profile.d/
    mode: '644'

- name: Copy vim bashrc
  ansible.builtin.copy:
    src: vim.bashrc
    dest: ~/.bashrc.d/
    mode: '644'

- name: Clean nvim config files
  ansible.builtin.file:
    path: '{{ item }}'
    state: absent
  with_items:
    - ~/.config/nvim
    - ~/.local/share/nvim
    - ~/.local/state/nvim
    - ~/.cache/nvim

- name: Setup nvim
  ansible.builtin.git:
    repo: 'https://github.com/maxdhn/nvim-config'
    dest: ~/.config/nvim
    depth: 1

# - name: Remove AstroNvim git connection
#   ansible.builtin.file:
#     path: ~/.config/nvim/.git
#     state: absent
