[colors.primary]
background = "#000000"

[font]
size = 11

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[shell]
args = ["-l", "-c", "tmux ls | grep -v attached && tmux attach || tmux"]
program = "/bin/bash"
