- name: Install misc packages
  become: true
  community.general.pacman:
    name:
      - xf86-input-synaptics
      - bluez
      - bluez-utils
      - iwd
      - ntfs-3g
      - cpio
      - man-db
      - archlinux-keyring
      - gnome-keyring
      - dnsmasq
      - dmidecode
      - openbsd-netcat

- name: Enable iwd systemd service
  become: true
  ansible.builtin.systemd:
    name: iwd
    enabled: true
  ignore_errors: '{{ ansible_check_mode }}'

- name: Enable bluetooth systemd service
  become: true
  ansible.builtin.systemd:
    name: bluetooth
    enabled: true
  ignore_errors: '{{ ansible_check_mode }}'

- name: Install ebtables
  become: true
  ansible.builtin.shell: yes | pacman -Sy ebtables
  args:
    creates: /usr/bin/ebtables
  tags:
    - skip_ansible_lint # can't use set -o pipefail
