- name: Install packages
  become: true
  community.general.pacman:
    name:
      - alacritty
      - tmux

# This because of extensive use of the --print-format :
# https://docs.ansible.com/ansible/latest/collections/community/general/pacman_module.html#parameter-executable
- name: Install tmux-bash-completion-git AUR package
  ansible.builtin.command: paru -Syu --noconfirm --nouseask tmux-bash-completion-git
  args:
    creates: /usr/share/bash-completion/completions/tmux

- name: Copy ps1.bashrc
  ansible.builtin.copy:
    src: ps1.bashrc
    dest: ~/.bashrc.d/
    mode: '644'

- name: Copy tmux conf
  ansible.builtin.copy:
    src: tmux.conf
    dest: ~/.config/tmux/
    mode: '644'

- name: Copy alacritty conf
  ansible.builtin.copy:
    src: alacritty.toml
    dest: ~/.config/alacritty/
    mode: '644'

- name: Copy alacritty bash_profile
  ansible.builtin.copy:
    src: alacritty.bash_profile
    dest: ~/.bash_profile.d/
    mode: '644'
